# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riddler/protobuf/content_management.proto

require 'google/protobuf'

require 'riddler/protobuf/content_version_pb'
require 'riddler/protobuf/slug_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riddler.protobuf.CreateContentVersionRequest" do
    optional :content_version, :message, 1, "riddler.protobuf.ContentVersion"
  end
  add_message "riddler.protobuf.CreateContentVersionResponse" do
  end
  add_message "riddler.protobuf.CreateSlugRequest" do
    optional :slug, :message, 1, "riddler.protobuf.Slug"
  end
  add_message "riddler.protobuf.CreateSlugResponse" do
  end
  add_message "riddler.protobuf.UpdateSlugRequest" do
    optional :slug, :message, 1, "riddler.protobuf.Slug"
  end
  add_message "riddler.protobuf.UpdateSlugResponse" do
  end
  add_message "riddler.protobuf.GetSlugStatsRequest" do
    optional :slug, :message, 1, "riddler.protobuf.Slug"
  end
  add_message "riddler.protobuf.GetSlugStatsResponse" do
    repeated :slug_stats, :message, 1, "riddler.protobuf.SlugStats"
  end
end

module Riddler
  module Protobuf
    CreateContentVersionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("riddler.protobuf.CreateContentVersionRequest").msgclass
    CreateContentVersionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("riddler.protobuf.CreateContentVersionResponse").msgclass
    CreateSlugRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("riddler.protobuf.CreateSlugRequest").msgclass
    CreateSlugResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("riddler.protobuf.CreateSlugResponse").msgclass
    UpdateSlugRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("riddler.protobuf.UpdateSlugRequest").msgclass
    UpdateSlugResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("riddler.protobuf.UpdateSlugResponse").msgclass
    GetSlugStatsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("riddler.protobuf.GetSlugStatsRequest").msgclass
    GetSlugStatsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("riddler.protobuf.GetSlugStatsResponse").msgclass
  end
end
