# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riddler/protobuf/content_version.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riddler.protobuf.ContentVersion" do
    optional :id, :string, 1
    optional :created_at, :message, 2, "google.protobuf.Timestamp"
    optional :content_type, :string, 3
    optional :content_id, :string, 4
    optional :version, :int32, 5
    optional :title, :string, 6
    optional :description, :string, 7
    optional :definition_schema_version, :int32, 8
    oneof :definition do
      optional :definition_string, :string, 9
    end
  end
end

module Riddler
  module Protobuf
    ContentVersion = Google::Protobuf::DescriptorPool.generated_pool.lookup("riddler.protobuf.ContentVersion").msgclass
  end
end
